### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by olivesfang** [AlexeyAB/yolo-windows#5]
I'm sorry, I'm relatively new to Visual Studio and am unsure of what steps I should take to compile. Is there a step by step guide? If not, currently I have CUDA 6.5 x64 installed (as well as 7.5) and OpenCV 2.4.9, and I'm trying to load the yolo-windows-master\build\darknet\darknet.sln with VS 2013, but to no luck. 

C:\Users(username)\Downloads\yolo-windows-master (vs2013, Cuda 6.5, Git AlexeyAB)\yolo-windows-master\build\darknet\darknet\darknet.vcxproj : error  : Unable to read the project file "darknet.vcxproj".

C:\Users(username)\Downloads\yolo-windows-master (vs2013, Cuda 6.5, Git AlexeyAB)\yolo-windows-master\build\darknet\darknet\darknet.vcxproj(55,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 6.5.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Any help is much appreciated. Thank you for your time.

EDIT: I wanted to add that I've installed YOLO on Ubuntu, so I have a (very vague) idea of how it should work. Main problem with that installation is, I could get my GPU to function within Virtual Box, and because I need web cam real-time detection in my work, I'm trying to install YOLO on windows instead.

**Comment by AlexeyAB** [comment]
@olivesfang 
1. Try to update build/darknet/darknet/darknet.vcxproj from last commit.
2. Try to delete all temporary files if it exist:
<proj>.vcxproj.user
<proj>.vcxproj.filters
<proj>.vcproj.<domainname???>.<username>.user
<proj>.suo
3. Open in MSVS 2013: darknet.vcxproj
then, right click on project -> Build dependecies -> Build Customizations -> set check on CUDA 6.5 or 7.0 - for example as here: http://devblogs.nvidia.com/parallelforall/wp-content/uploads/2015/01/VS2013-R-5.jpg

**Comment by olivesfang** [comment]
Thank you for your reply, I appreciate it a lot. However, after cloning the new commission, I still encounter the same problem. 

Also, here's the screenshot from step 3, when I open darknet.vcxproj in MSVS 2013. 
![image](https://cloud.githubusercontent.com/assets/19187878/19267057/3e3f5d5a-8fdf-11e6-8c2f-3ae578d1fbb0.png)

C:\Users(username)\Downloads\yolo-windows-master (vs2013, Cuda 6.5, Git AlexeyAB)\build\darknet\darknet\darknet.vcxproj : error  : Unable to read the project file "darknet.vcxproj".
C:\Users(username)\Downloads\yolo-windows-master (vs2013, Cuda 6.5, Git AlexeyAB)\build\darknet\darknet\darknet.vcxproj(55,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I noticed it's asking for CUDA 7.5 now, which I have installed, but it still won't load. I can't get to building dependencies either. 
![image](https://cloud.githubusercontent.com/assets/19187878/19267111/906e38b2-8fdf-11e6-866b-2906a8e6f42d.png)

I look forward to your reply, every bit of help is greatly appreciated. Thanks so much!

**Comment by AlexeyAB** [comment]
@olivesfang  Can you post screenshot from: HELP -> About Microsoft Visual Studio?
Is there Visual C++?

I just successfully opened darknet.sln in each of the: 
- MSVS2010 Ultimate
- MSVS2012 Ultimate Update 4
- MSVS2013 Ultimate SP1Rel

**Comment by olivesfang** [comment]
Here's the screenshot. I appreciate the response. 

![image](https://cloud.githubusercontent.com/assets/19187878/19306258/65f5fde0-90a7-11e6-957b-e0207c5e9a3a.png)

**Comment by AlexeyAB** [comment]
@olivesfang 
You can to create your own darknet.sln & darknet.vcxproj

Then add to your created project:
- (right click on project) -> properties  -> C/C++ -> General -> Additional Include Directories, put here: 

`C:\opencv_2.4.9\opencv\build\include;..\..\..\3rdparty\include;%(AdditionalIncludeDirectories);$(CudaToolkitIncludeDir)`
- right click on project -> Build dependecies -> Build Customizations -> set check on CUDA 7.5 or what version you have - for example as here: http://devblogs.nvidia.com/parallelforall/wp-content/uploads/2015/01/VS2013-R-5.jpg
- add to project all .c & .cu files from yolo-windows\src
-  (right click on project) -> properties  -> Linker -> General -> Additional Library Directories, put here: 

`C:\opencv_2.4.9\opencv\build\x64\vc12\lib;$(CUDA_PATH)lib\$(PlatformName);%(AdditionalLibraryDirectories)`
-  (right click on project) -> properties  -> Linker -> Input -> Additional dependecies, put here: 

`..\..\..\3rdparty\lib\x64\pthreadVC2.lib;cublas.lib;curand.lib;cudart.lib;%(AdditionalDependencies)`
- (right click on project) -> properties -> C/C++ -> Preprocessor -> Preprocessor Definitions

`OPENCV;_CRT_SECURE_NO_WARNINGS;GPU;WIN32;NDEBUG;_CONSOLE;_LIB;%(PreprocessorDefinitions)`
- compile to .exe (X64 & Release) and put .dll`s near with .exe:

`pthreadVC2.dll, pthreadGC2.dll` from yolo-windows\3rdparty\dll\x64

`cusolver64_75.dll, curand64_75.dll, cudart64_75.dll, cublas64_75.dll` - 75 for CUDA 7.5 or your version, from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin

**Comment by olivesfang** [comment]
Thank you for your reply ... but there are some steps that I do not understand. 
- What do you mean by `$(CUDA_PATH)lib\$(PlatformName);`? I ended up just adding that to my directories. 

> compile to .exe (X64 & Release) 
- You mean to build the project right? I don't understand if there are additional steps to make it "X64 & Release", can you direct me to a guide?

> `pthreadVC2.dll, pthreadGC2.dll` from yolo-windows\3rdparty\dll\x64
- But `pthreadGC2.dll` isn't in the specified folder? 

These are the output errors:
![image](https://cloud.githubusercontent.com/assets/19187878/19411252/b4159464-9330-11e6-82e7-4ffb34145421.png)
![image](https://cloud.githubusercontent.com/assets/19187878/19411334/6954aaa8-9332-11e6-94e2-102534a8f442.png)

I hope you are willing to continue to help me. Thank you so much for taking your time to teach me.

**Comment by AlexeyAB** [comment]
> What do you mean by $(CUDA_PATH)lib\$(PlatformName);? I ended up just adding that to my directories.

You should put exactly this line, not changing it.
`$(CUDA_PATH)lib\$(PlatformName);`

> compile to .exe (X64 & Release) You mean to build the project right? I don't understand if there are additional steps to make it "X64 & Release", can you direct me to a guide?

Yes, simply compile the project

> pthreadVC2.dll, pthreadGC2.dll from yolo-windows\3rdparty\dll\x64
> But pthreadGC2.dll isn't in the specified folder?

There are: pthreadGC2.dll, pthreadVC2.dll
https://github.com/AlexeyAB/yolo-windows/tree/master/3rdparty/dll/x64

> These are the output errors:

You should - I fixed it in my previous answer:

1. first thing, at the beginning: right click on project -> Build dependecies -> Build Customizations -> set check on CUDA 7.5 or what version you have - for example as here: http://devblogs.nvidia.com/parallelforall/wp-content/uploads/2015/01/VS2013-R-5.jpg

2. and only after 1-st step done, then: add to project all .c & .cu files from yolo-windows\src

And try to right click on any .cu-file -> properties, and you should see that there is CUDA C/C ++ compiler, not C/C++ compiler

**Comment by AlexeyAB** [comment]
@olivesfang 

> What do you mean by $(CUDA_PATH)lib\$(PlatformName);? I ended up just adding that to my directories.

You should put exactly this line, not changing it.
`$(CUDA_PATH)lib\$(PlatformName);`

> compile to .exe (X64 & Release) You mean to build the project right? I don't understand if there are additional steps to make it "X64 & Release", can you direct me to a guide?

Yes, simply compile the project

> pthreadVC2.dll, pthreadGC2.dll from yolo-windows\3rdparty\dll\x64
> But pthreadGC2.dll isn't in the specified folder?

There are: pthreadGC2.dll, pthreadVC2.dll
https://github.com/AlexeyAB/yolo-windows/tree/master/3rdparty/dll/x64

> These are the output errors:

You should - I fixed it in my previous answer:
1. first thing, at the beginning: right click on project -> Build dependecies -> Build Customizations -> set check on CUDA 7.5 or what version you have - for example as here: http://devblogs.nvidia.com/parallelforall/wp-content/uploads/2015/01/VS2013-R-5.jpg
2. and only after 1-st step done, then: add to project all .c & .cu files from yolo-windows\src

And try to right click on any .cu-file -> properties, and you should see that there is CUDA C/C ++ compiler, not C/C++ compiler

**Comment by olivesfang** [comment]
Thanks for the help, but I still encountered the exact error when following the new instructions. 

![image](https://cloud.githubusercontent.com/assets/19187878/19435534/bd7207fe-949d-11e6-81ea-17a7d8c39bf5.png)

![image](https://cloud.githubusercontent.com/assets/19187878/19435559/e295fd56-949d-11e6-8c17-1c2a9b2c5b7a.png)

![image](https://cloud.githubusercontent.com/assets/19187878/19435547/d4471f8c-949d-11e6-83ac-a868f149d03b.png)

Is it possible to watch you look into the project via Team Viewer? Thank you so much for the help so far.

**Comment by AlexeyAB** [comment]
@olivesfang 
Unfortunately I can not give remote access, even readonly.
- You must make sure that for each .cu-file selected compiler CUDA C/C++ instead of C/C++

(right click) on any .cu-file -> properties

![cudacpp](https://cloud.githubusercontent.com/assets/4096485/19439163/d38f9532-9485-11e6-9dd9-d4d528b1a071.jpg)
- And you must make sure that `cudart.lib` added:

![cudart](https://cloud.githubusercontent.com/assets/4096485/19439219/fc5c97c6-9485-11e6-86a8-56b65a4c8880.png)

Can you provide each screenshot for each of steps?
- selected compiler CUDA C/C++ for activation_kernels.cu (and check that the same for each .cu-file)
- Additional Include Directories
- Additional Library Directories
- Additional dependecies

**Comment by olivesfang** [comment]
> You must make sure that for each .cu-file selected compiler CUDA C/C++ instead of C/C++
> ![image](https://cloud.githubusercontent.com/assets/19187878/19441241/97237078-94b7-11e6-96bf-b85a95de580d.png)
> 
> And you must make sure that cudart.lib added:
> ![image](https://cloud.githubusercontent.com/assets/19187878/19441281/c476dd4e-94b7-11e6-8102-70f7ada401eb.png)
> 
> Additional Include Directories
> ![image](https://cloud.githubusercontent.com/assets/19187878/19441381/27d357f0-94b8-11e6-86c0-fdd638ab1013.png)
> 
> Additional Library Directories
> ![image](https://cloud.githubusercontent.com/assets/19187878/19441438/4b626a12-94b8-11e6-8adf-57ce6375f2e0.png)
> 
> Additional dependecies
> ![image](https://cloud.githubusercontent.com/assets/19187878/19441474/68a89088-94b8-11e6-8713-fcc1ad469837.png)

File path on my computer for OpenCV & yolo-windows for reference:
![image](https://cloud.githubusercontent.com/assets/19187878/19441501/7fdc4d44-94b8-11e6-8383-7b7f4561a206.png)
![image](https://cloud.githubusercontent.com/assets/19187878/19441541/a0a78d68-94b8-11e6-89b4-a48b62634abb.png)
![image](https://cloud.githubusercontent.com/assets/19187878/19441593/c6f7226c-94b8-11e6-81ff-295e0bdee5e9.png)

Thanks for the help again. I've also checked each .cu-file and it does say the item type is CUDA C/C++, although it'd take a while to screenshot all of them (I will upload them shortly.)

By Team Viewer, I meant if you would be so kind to access my computer and see if there is a problem. Thanks for the prompt help!

**Comment by AlexeyAB** [comment]
@olivesfang 

One last thing :)
- (right click on project) -> properties -> C/C++ ->  Preprocessor -> Preprocessor Definitions

Insert:

```
OPENCV
_CRT_SECURE_NO_WARNINGS
GPU
WIN32
NDEBUG
_CONSOLE
_LIB
```

**Comment by olivesfang** [comment]
Thanks! That allowed the project to start it's build. Unfortunately, it stopped shortly...

These are the error outputs: 
![image](https://cloud.githubusercontent.com/assets/19187878/19444565/8122e0cc-94c3-11e6-8d54-33615c36158e.png)

**Comment by AlexeyAB** [comment]
@olivesfang 
I fix some files in 2 last commits.
Try to download new versions of 3 files from github:
- src/utils.c
- src/maxpool_layer_kernels.cu
- src/softmax_layer_kernels.cu

**Comment by olivesfang** [comment]
Thanks again. After updating these files, this is the output error: 
![image](https://cloud.githubusercontent.com/assets/19187878/19450555/7e9fb154-94dc-11e6-86b3-e326c0eb7574.png)

I have checked the .cu and they are the correct item type.

**Comment by AlexeyAB** [comment]
@olivesfang 

In these files: `src/maxpool_layer_kernels.cu` & `src/softmax_layer_kernels.cu`, after all `#include`'s you can use:

```
#ifndef INFINITY
#include <limits>
const float INFINITY = std::numeric_limits<float>::infinity();
#endif
```

For example in  `src/softmax_layer_kernels.cu`:

```
#include "cuda_runtime.h"
#include "curand.h"
#include "cublas_v2.h"
#include "math.h"

extern "C" {
#include "maxpool_layer.h"
#include "cuda.h"
}

#ifndef INFINITY
#include <limits>
const float INFINITY = std::numeric_limits<float>::infinity();
#endif
```

---

Or try to use this `darknet2.vcxproj`

I just now did everything on his instructions on MSVS 2013 & CUDA 7.5 - and it works for x64 (Release & Debug), but not for Win32 (Release & Debug).
- Download: https://drive.google.com/open?id=0BwRgzHpNbsWBdGZuNkVnT1lUcnc
- Put it: yolo-windows\build\darknet2\darknet2\darknet2.vcxproj
- And set x64 to compile

**Comment by olivesfang** [comment]
Holy cow, I was able to compile darknet2.vcxproj successfully. Although ... the .exe file crashes upon execution and gives me the following errors regarding these files are missing and need to be re-installed:
- pthreadVC2.dll 
- opencv_core249.dll
- opencv_imgproc249.dll 
- opencv_highgui249.dll

If you have some time, please look into this. Thank you so much!

EDIT: I have the `pthreadVC2.dll` file at `yolo-windows-master\yolo-windows-master\3rdparty\dll\x64`
I see the opencv related `.dll` files are here `C:\opencv_2.4.9\opencv\build\x64\vc12\bin`

EDIT2: I was able to fix it easily by dragging the correct files to the root. Never mind! Currently having problems with execution, where the title + box won't appear (so it's not detecting at all ...)

**Comment by olivesfang** [comment]
Okay, so my executable doesn't seem to be detecting objects correctly. Real time webcam loaded, but wasn't detecting anything. Running the yolo test instead, I found prediction errors. 

This is the input:
![image](https://cloud.githubusercontent.com/assets/19187878/19886998/e6af7510-a060-11e6-9185-ed87b952c43f.png)

And the prediction variables:
![image](https://cloud.githubusercontent.com/assets/19187878/19887010/f6709a74-a060-11e6-9e0b-798a92ad85d2.png)

The output: 
![image](https://cloud.githubusercontent.com/assets/19187878/19887017/050cef38-a061-11e6-90c8-b1ce6631852e.png)

Thank you for looking into this!

**Comment by olivesfang** [comment]
Just reporting back that I was eventually able to compile with the original files in the repository with CUDA 7.5 and VS 2013. Thanks for the help!

**Comment by AlexeyAB** [comment]
@olivesfang Glad to hear. What was the problem and how it was solved? Now do you successfully detect the objects?

* Now by link there is new version YoloV2: http://pjreddie.com/darknet/yolo/
* But this fork of old version YoloV1, description is now here:  http://pjreddie.com/darknet/yolov1/

I changed all links to old weights-files in Readme.md (in the description of this fork) which successfully tested.
